- name: update-timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata
- name: reboot-required
  command: reboot
- name: restart postfix
  service:
    name: postfix
    state: restarted
  ignore_errors: true
